project:
  type: website
  output-dir: docs

website:
  title: "Rae L. Brotsky"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: undergrad_work.qmd
        text: Undergraduate Work
      - href: research.qmd
        text: Research Experience
      - href: creative_writing.qmd
        text: Creative Writing Portfolio
      - about.qmd

format:
  html:
    theme: 
      light: lux
      dark: darkly
    # css: styles.css
    toc: true
    page-layout: full